### ISSUE TITLE
Evaluate options for producing a native binary

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-cli#383]
## Description

As an AlgoKit developer
I want to evaluate the various options for [producing a native binary](https://github.com/algorandfoundation/algokit-cli/issues/384)
So that I'm informed of the tradeoffs of each approach

## Technical Details

Options to evaluate:
- PyInstaller
- cx_Freeze
- PyOxidizer
- Nuitka

Environments to Support:
- Windows (10+)
- MacOS (-1 from current)
- Linux - RPM Based - CentOS/RHEL
- Linux - Debian Based - Ubuntu/Fedora/Qubes OS (16.0.4+)
- Linux - Arch

Architectures to Support:
- x86
- x86_64
- arm64
- Apple silicon

## Acceptance Criteria

- A representative proof of concept has been built to assess suitability of each option
- Any findings/limitations/trade offs/problems that have been discovered are documented, allowing us to critically assess the options

## Tasks

- [x] Create a PyInstaller PoC @negar-abbasi
- [x] Create a cx_Freeze PoC
- [x] Create a PyOxidizer PoC
- [x] Create a Nuitka PoC

**Comment by aorumbayev** [comment]
separate adr on distribution via snap, brew, winget is to follow
