### ISSUE TITLE
MacOS users can easily install the native AlgoKit cli

### ISSUE THREAD

**Issue by neilcampbell** [algorandfoundation/algokit-cli#389]
## Description

As a MacOS user
I want to install the AlgoKit cli using brew
So that I have a seamless install and upgrade experience

## Acceptance Criteria

- The AlgoKit cli is available to install using brew
- The AlgoKit cli detects when an upgrade is available and the user can initiate an upgrade via brew
- Self update mechanism is implemented as per https://github.com/orgs/algorandfoundation/projects/1?pane=issue&itemId=44360946

## Tasks

Tasks
 - [x] Get familiar with codesign commands for mac os binaries. Enhance release ci pipeline to codesign the binary prior to release to brew tap (evaluate whether there is any value to instead parametrize the build artifact action to take care of codesigning step vs having dedicated step as part of the cd workflow). 
 - [x] Add support for apple silicon runners 
 - [x] Duplicate existing binary build action for mac to be run on a matrix that includes both arm64 and amd64 instead of current setup that relies on amd64 based macos-latest runner. This is to ensure we support apple silicon. Github has free runners on m1 available as of last week, refer to github actions docs for more info.
 - [x] Upgrade existing brew release flow by copying poc implementation from [fork commit](https://github.com/aorumbayev/algokit-cli/commit/2d25ea98e2eed6b0f8231ff1f2407706f2484c26) (sample [action run](https://github.com/aorumbayev/algokit-cli/actions/runs/7647995869) that publishes cask with binary in it instead of the wheel). Further polish and refine poc implementation by updating the cask definition to conditionally pick arm vs amd64 binary based on os architecture of the user during cask installation (see [refs](https://stackoverflow.com/questions/77629028/does-homebrew-cask-support-architecture-based-distribution-for-apple-silicon-and) on how to achieve that). 
 - [x] Explicitly verify brew behaviour when updating algokit installed from brew as a wheel vs a new brew version that is installed as a binary.  
 - [ ] Perform initial e2e release by incorporating signing using Apple developer certificates provided by @Loedn
 - [ ] Document new installation option on the main readme for mac and brew users.
