### ISSUE TITLE
Puya integration into algokit-cli, removing the need to install them explicitly

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-cli#400]
## Description

The goal is to ensure that `algokit-cli` handles installation of `puya-py` automatically and lazy-loads them as per usage.

## Technical Details

Using `algokit compile` uses approach similar to `algokit generate` where semantics are inferred based on file extension. `.py` -> puya. An alternate approach is to use `algokit compile py`, so the compiler is known when the command is executed. This also has the added benefit of be extensible for future support of other compilers that may require different arguments.

We want to integrate this into the cli once 1.0 of Puya has released and update the cli to v2.

## Acceptance Criteria

- [ ] A user is able to execute the puya compiler via `algokit-cli` and turn their PuyaPy smart contract into a deployable teal contract, without explicitly installing it by executing `algokit compile *.py`
- [ ] A user is able to discover any compilation issues in their PuyaPy contract using `algokit compile`

## Tasks

- [ ] PuyaPy compiler is integrated into the cli, usage is tested & documented

**Comment by PatrickDinh** [comment]
Reopen because this will be documented in v2 release.
