### ISSUE TITLE
Init wizard v2 - simplified experience for instantiating new templates

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-cli#412]
## Description

As a new user to algokit ecosystem i would like to have access to an interactive wizard that intuitively guides me through decision making process of picking the right tool to accomplish my goal.

## Technical Details

Improve user experience by making the wizard more intuitive and less reliant on Algorand-specific jargon.
Streamline the presets concept to minimize user inputs and simplify the process.

## Acceptance Criteria

- AlgoKit CLI provides a refined init wizard experience as part of the `init` invocation. 
- Interactive wizard refinements do not modify any of the existing capabilities of the `init` wizard other than focusing on more intuitive filtering of the `Blessed Template` to use.

## Tasks

- [x]  Improve PoC [implementation](https://github.com/algorandfoundation/algokit-cli/tree/feat/init_wizard_v2) 
- [x]  Update puya, react, fullstack templates  to support the flow and refinements in the presets. 
- [x]  Add approval tests & documentation 
- [x]  Evaluate complexity of turning `cloud_providers` into a generator
- [x] Revisit the need for further simplifying deployment scripts/logic in official puya template

**Comment by aorumbayev** [comment]
Addressed in https://github.com/algorandfoundation/algokit-cli/releases/tag/v1.12.1
