### ISSUE TITLE
Enable command orchestration within algokit compliant projects to be managed by algokit-cli

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-cli#417]
## Description

As a user of algokit-cli i would like to be able to rely on the cli to orchestrate invocation of common commands across all dependent `sub-projects`.

## Technical Details

- Expand the schema used in `.algokit.toml` settings file to add notion of project types and unique identifiers
- Evaluate options around sequential vs concurrent execution modes as well as ability to specify run order for commands with matching unique identifiers. 

## Acceptance Criteria

- Official AlgoKit templates (fullstack, puya, tealscript, react)
- AlgoKit CLI is able to parse `.algokit.toml` files to perform orchestration when run from root of a workspace and run direct command on a child sub proejct when run from within sub-project
 
## Tasks

- [ ] Improve PoC [implementation](https://github.com/algorandfoundation/algokit-cli/tree/feat/command_orchestration/src/algokit) 
- [ ] Update puya, react, fullstack templates  to contain new `.algokit.toml` settings
- [ ] Add approval tests & documentation

**Comment by aorumbayev** [comment]
done as part of algokit cli v2.0 release
